// This file was generated by a tool; you should avoid making direct changes.
// Consider using 'partial classes' to extend these types
// Input: my.proto

#pragma warning disable CS1591, CS0612, CS3021, IDE1006
namespace mhcc.app.dataprovider.model.tdiinterface.dstructs
{

    [global::ProtoBuf.ProtoContract()]
    public partial class LocalisedStringItem : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(1, IsRequired = true)]
        public string localeKey { get; set; }

        [global::ProtoBuf.ProtoMember(2, Name = @"value", IsRequired = true)]
        public string Value { get; set; }

    }

    [global::ProtoBuf.ProtoContract()]
    public partial class MultilingualString : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(1, IsRequired = true)]
        public string defaultValue { get; set; }

        [global::ProtoBuf.ProtoMember(3, Name = @"item")]
        public global::System.Collections.Generic.List<LocalisedStringItem> Items { get; } = new global::System.Collections.Generic.List<LocalisedStringItem>();

    }


    [global::ProtoBuf.ProtoContract()]
    public partial class PatternTdi : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(1, Name = @"duid", DataFormat = global::ProtoBuf.DataFormat.ZigZag, IsRequired = true)]
        public long Duid { get; set; }

        [global::ProtoBuf.ProtoMember(2, Name = @"last_modification_timestamp", DataFormat = global::ProtoBuf.DataFormat.ZigZag, IsRequired = true)]
        public long LastModificationTimestamp { get; set; }

        [global::ProtoBuf.ProtoMember(3, Name = @"is_deleted", IsRequired = true)]
        public bool IsDeleted { get; set; }

        [global::ProtoBuf.ProtoMember(80, Name = @"type", IsRequired = true)]
        public uint Type { get; set; }

        [global::ProtoBuf.ProtoMember(81, Name = @"short_name", IsRequired = true)]
        public string ShortName { get; set; }

        [global::ProtoBuf.ProtoMember(82, Name = @"long_name")]
        [global::System.ComponentModel.DefaultValue("")]
        public string LongName
        {
            get { return __pbn__LongName ?? ""; }
            set { __pbn__LongName = value; }
        }
        public bool ShouldSerializeLongName() => __pbn__LongName != null;
        public void ResetLongName() => __pbn__LongName = null;
        private string __pbn__LongName;

        [global::ProtoBuf.ProtoMember(83, Name = @"multilingual_passenger_name")]
        public MultilingualString MultilingualPassengerName { get; set; }

        [global::ProtoBuf.ProtoMember(84, Name = @"route_duid", IsRequired = true)]
        public Reference RouteDuid { get; set; }

        [global::ProtoBuf.ProtoMember(85, Name = @"direction", IsRequired = true)]
        public uint Direction { get; set; }

        [global::ProtoBuf.ProtoMember(86, Name = @"stop_points_duids")]
        public global::System.Collections.Generic.List<Reference> StopPointsDuids { get; } = new global::System.Collections.Generic.List<Reference>();

    }

    [global::ProtoBuf.ProtoContract()]
    public partial class PatternTdiArray : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(1, Name = @"patternTdiArray")]
        public global::System.Collections.Generic.List<PatternTdi> patternTdiArrays { get; } = new global::System.Collections.Generic.List<PatternTdi>();

    }

}

#pragma warning restore CS1591, CS0612, CS3021, IDE1006
