// This file was generated by a tool; you should avoid making direct changes.
// Consider using 'partial classes' to extend these types
// Input: my.proto

#pragma warning disable CS1591, CS0612, CS3021, IDE1006
namespace mhcc.app.protobuf.commons
{

    [global::ProtoBuf.ProtoContract()]
    public partial class Reference : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(1, IsRequired = true)]
        public int structTag { get; set; }

        [global::ProtoBuf.ProtoMember(2, Name = @"duid", DataFormat = global::ProtoBuf.DataFormat.ZigZag, IsRequired = true)]
        public long Duid { get; set; }

    }

    [global::ProtoBuf.ProtoContract()]
    public partial class ValueObject : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(1, IsRequired = true)]
        public int structTag { get; set; }

        [global::ProtoBuf.ProtoMember(2, Name = @"value", IsRequired = true)]
        public byte[] Value { get; set; }

    }

}

#pragma warning restore CS1591, CS0612, CS3021, IDE1006
