using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

// This file was generated by a tool; you should avoid making direct changes.
// Consider using 'partial classes' to extend these types
// Input: my.proto

#pragma warning disable CS1591, CS0612, CS3021, IDE1006
namespace mhcc.app.dataprovider.model.tdiinterface.dstructs
{

    [global::ProtoBuf.ProtoContract()]
    public partial class Reference : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(1, IsRequired = true)]
        public int structTag { get; set; }

        [global::ProtoBuf.ProtoMember(2, Name = @"duid", DataFormat = global::ProtoBuf.DataFormat.ZigZag, IsRequired = true)]
        public long Duid { get; set; }

    }

    [global::ProtoBuf.ProtoContract()]
    public partial class ValueObject : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(1, IsRequired = true)]
        public int structTag { get; set; }

        [global::ProtoBuf.ProtoMember(2, Name = @"value", IsRequired = true)]
        public byte[] Value { get; set; }

    }

    [global::ProtoBuf.ProtoContract()]
    public partial class VehicleTdi : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(1, Name = @"duid", DataFormat = global::ProtoBuf.DataFormat.ZigZag, IsRequired = true)]
        public long Duid { get; set; }

        [global::ProtoBuf.ProtoMember(2, Name = @"last_modification_timestamp", DataFormat = global::ProtoBuf.DataFormat.ZigZag, IsRequired = true)]
        public long LastModificationTimestamp { get; set; }

        [global::ProtoBuf.ProtoMember(3, Name = @"is_deleted", IsRequired = true)]
        public bool IsDeleted { get; set; }

        [global::ProtoBuf.ProtoMember(32, Name = @"category")]
        public uint Category
        {
            get { return __pbn__Category.GetValueOrDefault(); }
            set { __pbn__Category = value; }
        }
        public bool ShouldSerializeCategory() => __pbn__Category != null;
        public void ResetCategory() => __pbn__Category = null;
        private uint? __pbn__Category;

        [global::ProtoBuf.ProtoMember(33, Name = @"trip_duid")]
        public Reference TripDuid { get; set; }

        [global::ProtoBuf.ProtoMember(34, Name = @"geo_position_status", IsRequired = true)]
        public uint GeoPositionStatus { get; set; }

        [global::ProtoBuf.ProtoMember(35, Name = @"reference_time", IsRequired = true)]
        public ulong ReferenceTime { get; set; }

        [global::ProtoBuf.ProtoMember(36, Name = @"latitude", DataFormat = global::ProtoBuf.DataFormat.ZigZag)]
        public int Latitude
        {
            get { return __pbn__Latitude.GetValueOrDefault(); }
            set { __pbn__Latitude = value; }
        }
        public bool ShouldSerializeLatitude() => __pbn__Latitude != null;
        public void ResetLatitude() => __pbn__Latitude = null;
        private int? __pbn__Latitude;

        [global::ProtoBuf.ProtoMember(37, Name = @"longitude", DataFormat = global::ProtoBuf.DataFormat.ZigZag)]
        public int Longitude
        {
            get { return __pbn__Longitude.GetValueOrDefault(); }
            set { __pbn__Longitude = value; }
        }
        public bool ShouldSerializeLongitude() => __pbn__Longitude != null;
        public void ResetLongitude() => __pbn__Longitude = null;
        private int? __pbn__Longitude;

        [global::ProtoBuf.ProtoMember(38, Name = @"bearing")]
        public uint Bearing
        {
            get { return __pbn__Bearing.GetValueOrDefault(); }
            set { __pbn__Bearing = value; }
        }
        public bool ShouldSerializeBearing() => __pbn__Bearing != null;
        public void ResetBearing() => __pbn__Bearing = null;
        private uint? __pbn__Bearing;

        [global::ProtoBuf.ProtoMember(39, Name = @"is_accessible")]
        public uint IsAccessible
        {
            get { return __pbn__IsAccessible.GetValueOrDefault(); }
            set { __pbn__IsAccessible = value; }
        }
        public bool ShouldSerializeIsAccessible() => __pbn__IsAccessible != null;
        public void ResetIsAccessible() => __pbn__IsAccessible = null;
        private uint? __pbn__IsAccessible;

        [global::ProtoBuf.ProtoMember(40, Name = @"pattern_duid")]
        public Reference PatternDuid { get; set; }

        [global::ProtoBuf.ProtoMember(41, Name = @"has_bike_rack")]
        public uint HasBikeRack
        {
            get { return __pbn__HasBikeRack.GetValueOrDefault(); }
            set { __pbn__HasBikeRack = value; }
        }
        public bool ShouldSerializeHasBikeRack() => __pbn__HasBikeRack != null;
        public void ResetHasBikeRack() => __pbn__HasBikeRack = null;
        private uint? __pbn__HasBikeRack;

        [global::ProtoBuf.ProtoMember(42, Name = @"vehicle_number")]
        public uint VehicleNumber
        {
            get { return __pbn__VehicleNumber.GetValueOrDefault(); }
            set { __pbn__VehicleNumber = value; }
        }
        public bool ShouldSerializeVehicleNumber() => __pbn__VehicleNumber != null;
        public void ResetVehicleNumber() => __pbn__VehicleNumber = null;
        private uint? __pbn__VehicleNumber;

        [global::ProtoBuf.ProtoMember(96, Name = @"operational_number")]
        public uint OperationalNumber
        {
            get { return __pbn__OperationalNumber.GetValueOrDefault(); }
            set { __pbn__OperationalNumber = value; }
        }
        public bool ShouldSerializeOperationalNumber() => __pbn__OperationalNumber != null;
        public void ResetOperationalNumber() => __pbn__OperationalNumber = null;
        private uint? __pbn__OperationalNumber;

    }

}

#pragma warning restore CS1591, CS0612, CS3021, IDE1006
