// This file was generated by a tool; you should avoid making direct changes.
// Consider using 'partial classes' to extend these types
// Input: my.proto

#pragma warning disable CS1591, CS0612, CS3021, IDE1006
namespace mhcc.app.dataprovider.model.tdiinterface.dstructs
{

    [global::ProtoBuf.ProtoContract()]
    public partial class VersionTdi : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(1, Name = @"duid", DataFormat = global::ProtoBuf.DataFormat.ZigZag, IsRequired = true)]
        public long Duid { get; set; }

        [global::ProtoBuf.ProtoMember(2, Name = @"last_modification_timestamp", DataFormat = global::ProtoBuf.DataFormat.ZigZag, IsRequired = true)]
        public long LastModificationTimestamp { get; set; }

        [global::ProtoBuf.ProtoMember(3, Name = @"is_deleted", IsRequired = true)]
        public bool IsDeleted { get; set; }

        [global::ProtoBuf.ProtoMember(32, Name = @"base_version")]
        public ulong BaseVersion
        {
            get { return __pbn__BaseVersion.GetValueOrDefault(); }
            set { __pbn__BaseVersion = value; }
        }
        public bool ShouldSerializeBaseVersion() => __pbn__BaseVersion != null;
        public void ResetBaseVersion() => __pbn__BaseVersion = null;
        private ulong? __pbn__BaseVersion;

    }

}

#pragma warning restore CS1591, CS0612, CS3021, IDE1006
